### ISSUE TITLE
The Select Categories By Parent option results in error

### ISSUE THREAD

**Issue by avstaylime** [ParadoxLabs-Inc/pagebuilder-widgets#4]
Selecting the _parent_ option results in `Error filtering template: Please select a parent category to display`.

![image](https://github.com/ParadoxLabs-Inc/pagebuilder-widgets/assets/82515176/1e161226-21e7-4523-99f4-db3dbb1ca32e)
![image](https://github.com/ParadoxLabs-Inc/pagebuilder-widgets/assets/82515176/b54eec12-6456-4166-84fa-e31e5a8b4cf4)

Magento 2.4.6-p3

**Comment by rhoerr** [comment]
Please try https://github.com/ParadoxLabs-Inc/pagebuilder-widgets/commit/699b967c479246d60bd03fb63ca86d66936bfb65

**Comment by avstaylime** [comment]
It has worked. Thanks!
