### ISSUE TITLE
Switching from 'Category' to 'Parent Category' produces unexpected results in 'Show Subcategories of'

### ISSUE THREAD

**Issue by avstaylime** [ParadoxLabs-Inc/pagebuilder-widgets#5]
As shown below, 'Show Subcategories of' being a single-select field inherits all the categories from 'Category'.
<img width="690" alt="image" src="https://github.com/ParadoxLabs-Inc/pagebuilder-widgets/assets/82515176/a311e41b-15ab-468b-8a26-2c695fa9b691">
<img width="705" alt="image" src="https://github.com/ParadoxLabs-Inc/pagebuilder-widgets/assets/82515176/d91e4d73-58fb-4e35-bd42-763a681726f6">

**Comment by rhoerr** [comment]
I think this is also fixed by 699b967c479246d60bd03fb63ca86d66936bfb65 actually. The single-category field was erroneously connected to the multi-category value previously.

Please confirm, and I'll push an update for it. Thanks!

**Comment by avstaylime** [comment]
It has worked. Thanks!
